---
- name: NAGIOS | Include OS-specific variables.
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}_{{ansible_distribution_major_version}}_{{ansible_distribution_minor_version}}.yml"
    - "{{ansible_distribution}}_{{ansible_distribution_major_version}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}_{{ansible_distribution_major_version}}_{{ansible_distribution_minor_version}}.yml"
    - "{{ansible_os_family}}_{{ansible_distribution_major_version}}.yml"
    - "{{ansible_os_family}}.yml"
    - "default.yml"
  tags:
    - nagios

- include: register/main.yml
- include: install/main.yml
- include: nagios/main.yml

## Check latest nagios version
## Get current nrpe version
## Check latest nrpe version
## Get current nagiosgraph version
## Check latest nagiosgraph version
## Get current nagiosplugins version
## Check latest nagiosplugins verison

# Nrpe

# Nagiosgraph

# Client checks
