# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# Variables
#
VAGRANTFILE_API_VERSION = "2"
LOCAL_BOX_DIRECTORY = "file://~/Downloads/"

TEST_MODE = false

NETWORK_PRIVATE_IP_PREFIX = "172.16.3."
PROVIDER_UNDER_TEST = "virtualbox"

DESTINATION_DIR = "/etc/ansible/roles/role_under_test"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 3
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  # Ubuntu 16.04 - Xenial Xerus
  config.vm.define "ubuntu1604" do |ubuntu1604|

    ubuntu1604.vm.hostname = "ubuntu1604"

    if not TEST_MODE
      ubuntu1604.vm.box = "geerlingguy/ubuntu1604"
    else
      ubuntu1604.vm.box = LOCAL_BOX_DIRECTORY + PROVIDER_UNDER_TEST + "-ubuntu1604.box"
    end

    ubuntu1604.vm.synced_folder "../", "/etc/ansible/roles/role_under_test", type: 'virtualbox'
    ubuntu1604.vm.network :private_network, ip: NETWORK_PRIVATE_IP_PREFIX + "2"

    # Install epel / ansible / and run the playbook
    ubuntu1604.vm.provision "shell", inline: <<-SHELL
      apt-get install -y vim ansible
      cd /etc/ansible/roles/role_under_test/tests/ && ansible-playbook vagrant_test.yml
    SHELL

  end

  # Ubuntu 14.04 - Trusty Tahr
  config.vm.define "ubuntu1404" do |ubuntu1404|
    ubuntu1404.vm.hostname = "ubuntu1404"

    if not TEST_MODE
      ubuntu1404.vm.box = "geerlingguy/ubuntu1404"
    else
      ubuntu1404.vm.box = LOCAL_BOX_DIRECTORY + PROVIDER_UNDER_TEST + "-ubuntu1404.box"
    end

    ubuntu1404.vm.synced_folder "../", "/etc/ansible/roles/role_under_test", type: 'virtualbox'
    ubuntu1404.vm.network :private_network, ip: NETWORK_PRIVATE_IP_PREFIX + "3"

    # Install epel / ansible / and run the playbook
    ubuntu1404.vm.provision "shell", inline: <<-SHELL
      apt-get install -y vim ansible
      cd /etc/ansible/roles/role_under_test/tests/ && ansible-playbook vagrant_test.yml
    SHELL

  end

  # Ubuntu 12.02 - Precise Pangolin
  config.vm.define "ubuntu1204" do |ubuntu1204|

    ubuntu1204.vm.hostname = "ubuntu1204test"

    if not TEST_MODE
      ubuntu1204.vm.box = "geerlingguy/ubuntu1204"
    else
      ubuntu1204.vm.box = LOCAL_BOX_DIRECTORY + PROVIDER_UNDER_TEST + "-ubuntu1204.box"
    end

    ubuntu1204.vm.synced_folder "../", "/etc/ansible/roles/role_under_test", type: 'virtualbox'
    ubuntu1204.vm.network :private_network, ip: NETWORK_PRIVATE_IP_PREFIX + "4"

    # Install epel / ansible / and run the playbook
    ubuntu1204.vm.provision "shell", inline: <<-SHELL
      apt-get install -y vim ansible
      cd /etc/ansible/roles/role_under_test/tests/ && ansible-playbook vagrant_test.yml
    SHELL

  end

  # CentOS 7
  config.vm.define "centos7" do |centos7|

    centos7.vm.hostname = "centos7"

    if not TEST_MODE
      centos7.vm.box = "geerlingguy/centos7"
    else
      centos7.vm.box = LOCAL_BOX_DIRECTORY + PROVIDER_UNDER_TEST + "-centos7.box"
    end

    centos7.vm.synced_folder "../", "/etc/ansible/roles/role_under_test", type: 'virtualbox'
    centos7.vm.network :private_network, ip: NETWORK_PRIVATE_IP_PREFIX + "5"

    # Install epel / ansible / and run the playbook
    config.vm.provision "shell", inline: <<-SHELL
      yum install -y epel-release
      yum install -y vim ansible
    SHELL

    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/etc/ansible/roles/role_under_test/tests/test.yml"
    end
  end

  # CentOS 6
  config.vm.define "centos6" do |centos6|

    centos6.vm.hostname = "centos6"

    if not TEST_MODE
      centos6.vm.box = "geerlingguy/centos6"
    else
      centos6.vm.box = LOCAL_BOX_DIRECTORY + PROVIDER_UNDER_TEST + "-centos6.box"
    end

    centos6.vm.synced_folder "../", "/etc/ansible/roles/role_under_test", type: 'virtualbox'
    centos6.vm.network :private_network, ip: NETWORK_PRIVATE_IP_PREFIX + "6"

    # Install epel / ansible / and run the playbook
    config.vm.provision "shell", inline: <<-SHELL
      yum install -y epel-release
      yum install -y vim ansible
    SHELL

    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/etc/ansible/roles/role_under_test/tests/test.yml"
      ansible_playbook = "/etc/ansible/roles/role_under_test/tests/test-assertions.yml"
    end

  end

end
