---
- name: NAGIOS | Add NRPE Group
  group:
    name: "{{nrpe_group | default('nrpe')}}"
    gid: "{{nrpe_group_gid | default('676')}}"
    system: yes
    state: present

- name: NAGIOS | Add NRPE User
  user:
    name: "{{nrpe_user | default('nrpe')}}"
    uid: "{{nrpe_user_uid | default('676')}}"
    system: yes
    groups: nagios
    state: present
    home: "{{nagios_prefix}}"

- name: NAGIOS | Install nagios.cfg from template
  template:
    src: nagios_cfg.j2
    dest: "{{nagios_core_prefix}}/etc/nagios.cfg"
    owner: nagios
    group: nagios
    mode: 0660
